services:
  vue-admin-panel:
    container_name: vuejs_dashboard
    image: vuejs_dashboard:latest
    build:
      context: ./ 
      dockerfile: Dockerfile
    env_file:
      - .env 
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    restart: on-failure
    networks:
      - vueapp_network

networks:
  vueapp_network:
    driver: bridge