services:
  nuxt-panel:
    container_name: nuxt-panel
    image: nuxt-panel:latest
    build:
      context: ./ 
      dockerfile: Dockerfile
    env_file:
      - .env 
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    restart: on-failure
    networks:
      - nuxtapp_network

networks:
  nuxtapp_network:
    driver: bridge